### ISSUE TITLE
Repo with design materials

### ISSUE THREAD

**Issue by HaySayCheese** [0xCompany/0xProposals#2]
**Short, but complete description**
We are declaring openness in all, so the design-related things should not be an exception.  

**Why?**
1. This materials can be used by community for staff-making (t-shorts, etc)
1. This materials can be used by followers to brand their mentions about us in social networks.
1. This materials would be useful for us in the future.
1. It would be nice to have all graphics-related stuff in one place. 

**What kind and how many resources are needed?**
1. 20 minutes to create and describe a repo.
2. 30 minutes to create folders structure and fill it up.

**Priority?**
75

**Comment by SerhiiMeketiuk** [comment]
https://github.com/0xCompany/0xDesign
